### ISSUE TITLE
Error v1.12-R0.1 on refresh

### ISSUE THREAD

**Issue by Flynrod** [aadnk/ProtocolLib#135]
Hello,

When I **refresh the list of my Minecraft** servers, I get an error in the console: [https://pastebin.com/heqK59xH](https://pastebin.com/heqK59xH)

**Comment by MiniDigger** [comment]
This is not a protocollib issue but caused by featherspawn. I can't tell you more because the author stupidly decided to obfuscate his source.

**Comment by Flynrod** [comment]
So... Well... I am the autor of FeatherSpawn lol xD
It's TinyProtocol and not ProtocolLib :/
Video: https://www.youtube.com/watch?v=BVaPd4HY7Ho

Error log (without obfuscation): https://pastebin.com/dsBJsSQE

**Comment by MiniDigger** [comment]
That's why you always include all relevant information ;) 
Tinyprotocol wasn't touched for a year, guess it's time for an adjustment. There are other issues on the fork that could be related.

**Comment by Alvin-LB** [comment]
Do believe it's the same issue that this commit fixed in ProtocolLib (line 147):
https://github.com/aadnk/ProtocolLib/commit/b4f9c501b3dd33ff740b917c6ba83cfb99977e61

Although since that is a temporary fix, I'm unsure if it's wise to implement it into TinyProtocol, and maybe one should instead wait for a proper fix. But in the mean time, if you just add the "channel.eventLoop().submit()" around the statement at line 132 in TinyProtocol.java it should at least work.

**Comment by dmulloy2** [comment]
Should be fixed here: https://github.com/dmulloy2/ProtocolLib/commit/cd2f56d7c78fba228912b875270a225764318a4e

**Comment by Flynrod** [comment]
Thank's it work! :)
