### ISSUE TITLE
send player?

### ISSUE THREAD

**Issue by SkymaxPlay** [aadnk/ProtocolLib#91]
Hello,
Can I send player to another server using plugin with ProtocolLib?

**Comment by aadnk** [comment]
No, not in vanilla Minecraft.

If you also control the destination server, you might want to look at using (BungeeCord)[https://www.spigotmc.org/wiki/bungeecord/]. That allows you to transfer players within a group of servers you control using a front-end proxy server.

**Comment by SkymaxPlay** [comment]
Even if I used socket and netty?

**Comment by aadnk** [comment]
Perhaps I worded that a bit too strongly.

Theoretically, you could do the same as BungeeCord, and just connect to the server on the players behalf while proxying all packets back and forth. The problem is that you can't authenticate as the player if the server is in online mode (you don't have its [access token](http://wiki.vg/Protocol_Encryption)), so you would have to use a Minecraft account of your own. This would involve logging in to the other server under your name, while allowing the player to control and see your player through the proxy mechanism.

I don't think all of that is needed for offline servers, though.

**Comment by SkymaxPlay** [comment]
I need only send Player to Server. Proxying packet is required?

**Comment by SkymaxPlay** [comment]
I do not need online-mode

**Comment by MiniDigger** [comment]
Why don't you want to use BungeeCord for your problem? Would be way easier...

**Comment by SkymaxPlay** [comment]
Because:
1. I have to have one more server for bungee engine
2. When I connect to the server, not by bungee I can not go to another server

**Comment by MiniDigger** [comment]
1.When you use ProtocolLib to proxy the packets you will have the same load as if you would have using Bungee, maybe even more.
2. Just prevent ppl from joining your server without going through  Bungee first (iptables, plugin etc)

**Comment by SkymaxPlay** [comment]
2. But I do not want to prevent it, I need this

**Comment by MiniDigger** [comment]
you don't seem to understand me...
you you want to connect multiple servers, use bungee. useing protcollib would be way to compilcated and has no benefits over bungee.

**Comment by SkymaxPlay** [comment]
You understand, I need plugin Where I could Connect to another server

**Comment by MiniDigger** [comment]
if you use BungeeCord it is as simple as this:
```
final ByteArrayDataOutput out = ByteStreams.newDataOutput();
out.writeUTF("Connect");
out.writeUTF(server);
player.sendPluginMessage(plugin, "BungeeCord", out.toByteArray());
´´´
